'use client';

import React from 'react';

export interface ThemeProviderProps {
  children: React.ReactNode;
}

/**
 * Theme provider for Entangle UI components.
 *
 * The dark theme is applied globally via CSS custom properties on `:root`.
 * This provider is a simple pass-through — most apps don't need it.
 *
 * For scoped theme overrides, use `VanillaThemeProvider` with a custom
 * class generated by `createCustomTheme()`.
 */
export const ThemeProvider: React.FC<ThemeProviderProps> = ({ children }) => {
  return <>{children}</>;
};
