'use client';

import React, { useEffect } from 'react';

import { KeyboardContextProvider } from '@/context/KeyboardContext';

import { GLOBAL_SCROLLBARS_CLASS } from './globalScrollbars.css';

export interface ThemeProviderProps {
  children: React.ReactNode;
  /**
   * When true, apply Entangle's dark-theme scrollbar styling globally
   * (thin 8px track, muted thumb). The class is added to
   * `document.body` and removed on unmount.
   *
   * Opt-in by design: many app shells run alongside other UI
   * frameworks where forcing scrollbar styles would be invasive.
   *
   * @default false
   */
  globalScrollbars?: boolean;
}

/**
 * Theme provider for Entangle UI components.
 *
 * The dark theme's `--etui-*` custom properties are registered on `:root`
 * by the canonical stylesheet — `import 'entangle-ui/styles.css'` once at your
 * app root. With that loaded this provider is optional and acts as a
 * pass-through for most apps; use it to opt into additional global behaviors
 * such as native-scrollbar theming (`globalScrollbars`) and keyboard context.
 *
 * For scoped theme overrides, use `VanillaThemeProvider` with a custom
 * class generated by `createCustomTheme()`.
 */
export const ThemeProvider: React.FC<ThemeProviderProps> = ({
  children,
  globalScrollbars = false,
}) => {
  useEffect(() => {
    if (!globalScrollbars) return;
    if (typeof document === 'undefined') return;

    const body = document.body;
    body.classList.add(GLOBAL_SCROLLBARS_CLASS);
    return () => {
      body.classList.remove(GLOBAL_SCROLLBARS_CLASS);
    };
  }, [globalScrollbars]);

  return <KeyboardContextProvider>{children}</KeyboardContextProvider>;
};
