// src/index.ts
// Theme system (Vanilla Extract)
export {
  vars,
  darkThemeValues,
  createCustomTheme,
  VanillaThemeProvider,
  ThemeProvider,
} from '@/theme';
export type {
  ThemeVars,
  DarkThemeValues,
  VanillaThemeProviderProps,
  ThemeProviderProps,
} from '@/theme';

// Primitives
export {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
  Divider,
  Flex,
  Grid,
  ListItem,
  PageHeader,
  PanelSurface,
  ScrollArea,
  Spacer,
  SplitPane,
  SplitPanePanel,
  Stack,
} from '@/components/layout';
export {
  Badge,
  Button,
  Checkbox,
  CheckboxGroup,
  Code,
  Collapsible,
  Icon,
  IconButton,
  Input,
  Paper,
  Popover,
  PopoverClose,
  PopoverContent,
  PopoverTrigger,
  Radio,
  RadioGroup,
  Switch,
  Text,
  TextArea,
  Tooltip,
} from '@/components/primitives';
export {
  ColorPicker,
  ColorSwatch,
  EyeDropper,
  ColorPalette,
  MATERIAL_PALETTE,
  TAILWIND_PALETTE,
  PASTEL_PALETTE,
  EARTH_PALETTE,
  NEON_PALETTE,
  MONOCHROME_PALETTE,
  SKIN_TONES_PALETTE,
  VINTAGE_PALETTE,
  PROFESSIONAL_PALETTES,
  NumberInput,
  Select,
  Slider,
  VectorInput,
  TreeView,
  CurveEditor,
  CURVE_PRESETS,
  evaluateCurve,
  sampleCurve,
  createLinearCurve,
  domainToCanvas,
  CartesianPicker,
} from '@/components/controls';
export {
  ContextMenu,
  Menu,
  useContextMenuTarget,
  useMenu,
  Tab,
  TabList,
  TabPanel,
  Tabs,
} from '@/components/navigation';
export { FormHelperText, FormLabel, InputWrapper } from '@/components/form';
export {
  Dialog,
  DialogBody,
  DialogClose,
  DialogFooter,
  DialogHeader,
  EmptyState,
  Skeleton,
  SkeletonGroup,
  Spinner,
  ToastProvider,
  useToast,
} from '@/components/feedback';
export {
  PropertyGroup,
  PropertyPanel,
  PropertyRow,
  PropertySection,
  usePropertyUndo,
  ViewportGizmo,
  eulerToRotationMatrix,
  projectToCanvas,
  projectAxes,
  gizmoHitTest,
  presetViewToOrientation,
  quaternionToEuler,
  axisToPresetView,
  ChatPanel,
  ChatMessageList,
  ChatMessage,
  ChatBubble,
  ChatInput,
  ChatTypingIndicator,
  ChatToolCall,
  ChatCodeBlock,
  ChatAttachmentChip,
  ChatContextChip,
  ChatEmptyState,
  ChatActionBar,
  ChatInputToolbar,
  ChatMarkdownRenderer,
  useChatMessages,
  useChatInput,
  useChatScroll,
} from '@/components/editor';
export {
  AppShell,
  useAppShell,
  FloatingManager,
  FloatingPanel,
  MenuBar,
  StatusBar,
  Toolbar,
} from '@/components/shell';

export type {
  AccordionContentProps,
  AccordionItemProps,
  AccordionProps,
  AccordionSize,
  AccordionTriggerProps,
  AccordionVariant,
  DividerOrientation,
  DividerProps,
  DividerSpacing,
  DividerVariant,
  FlexAlign,
  FlexAlignContent,
  FlexDirection,
  FlexJustify,
  FlexProps,
  FlexSpacing,
  FlexWrap,
  GridProps,
  GridSize,
  GridSpacing,
  ListItemDensity,
  ListItemProps,
  PageHeaderProps,
  PageHeaderSize,
  PanelSurfaceBodyProps,
  PanelSurfaceFooterProps,
  PanelSurfaceHeaderProps,
  PanelSurfaceProps,
  PanelSurfaceSize,
  ScrollAreaDirection,
  ScrollAreaProps,
  ScrollbarVisibility,
  SplitDirection,
  SplitPanePanelProps,
  SplitPaneProps,
  PanelConfig,
  PanelSize,
} from '@/components/layout';
export type {
  BadgeColor,
  BadgeProps,
  BadgeSize,
  BadgeVariant,
  ButtonProps,
  ButtonSize,
  ButtonVariant,
  CheckboxGroupProps,
  CheckboxProps,
  CheckboxSize,
  CheckboxVariant,
  CodeProps,
  CodeSize,
  CollapsibleProps,
  CollapsibleSize,
  CollisionAvoidance,
  IconProps,
  IconSize,
  InputProps,
  InputSize,
  PaperElevation,
  PaperNestLevel,
  PaperProps,
  PaperSpacing,
  PopoverCloseProps,
  PopoverContentProps,
  PopoverPlacement,
  PopoverProps,
  PopoverTriggerProps,
  RadioGroupOrientation,
  RadioGroupProps,
  RadioLabelPosition,
  RadioProps,
  RadioSize,
  SwitchProps,
  SwitchSize,
  TextAlign,
  TextAreaProps,
  TextAreaResize,
  TextAreaSize,
  TextColor,
  TextElement,
  TextLineHeight,
  TextProps,
  TextSize,
  TextVariant,
  TextWeight,
  TooltipCollisionConfig,
  TooltipCollisionStrategy,
  TooltipPlacement,
  TooltipProps,
} from '@/components/primitives';
export type {
  ColorFormat,
  ColorInputMode,
  ColorPickerProps,
  ColorPickerSize,
  ColorPreset,
  ColorSwatchProps,
  EyeDropperProps,
  ColorPaletteProps,
  Palette,
  PaletteColor,
  PaletteShade,
  NumberInputProps,
  SelectProps,
  SelectSize,
  SelectVariant,
  SelectOptionItem,
  SelectOptionGroup,
  SliderProps,
  VectorInputProps,
  VectorInputSize,
  VectorDimension,
  VectorLabelPreset,
  VectorColorPreset,
  TreeViewProps,
  TreeViewSize,
  TreeNodeData,
  TreeNodeState,
  TreeSelectionMode,
  CurveEditorProps,
  CurveEditorSize,
  CurveData,
  CurveKeyframe,
  TangentMode,
  CurvePreset,
  CurveBackgroundInfo,
  CurveBottomBarInfo,
  CartesianPickerProps,
  CartesianPickerSize,
  CartesianPickerInfo,
} from '@/components/controls';
export type {
  ContextMenuBaseProps,
  ContextMenuConfig,
  ContextMenuProps,
  ContextMenuTargetDetails,
  UseContextMenuTargetResult,
  MenuProps,
  MenuBaseProps,
  MenuConfig,
  MenuGroup,
  MenuItem,
  MenuSelection,
  ItemSelectionType,
  SubmenuTrigger,
  TabListProps,
  TabPanelProps,
  TabProps,
  TabsProps,
  TabsSize,
  TabsVariant,
} from '@/components/navigation';
export type {
  FormHelperTextProps,
  FormLabelProps,
  InputWrapperProps,
} from '@/components/form';
export type {
  DialogBodyProps,
  DialogFooterProps,
  DialogHeaderProps,
  DialogProps,
  DialogSize,
  EmptyStateProps,
  EmptyStateVariant,
  SkeletonAnimation,
  SkeletonGroupProps,
  SkeletonProps,
  SkeletonShape,
  SpinnerColor,
  SpinnerProps,
  SpinnerSize,
  SpinnerVariant,
  ToastData,
  ToastPosition,
  ToastProviderProps,
  ToastSeverity,
  UseToastReturn,
} from '@/components/feedback';
export type {
  PropertyGroupProps,
  PropertyInspectorSize,
  PropertyPanelProps,
  PropertyRowProps,
  PropertySectionProps,
  PropertyUndoEntry,
  UsePropertyUndoOptions,
  UsePropertyUndoReturn,
  ViewportGizmoProps,
  ViewportGizmoSize,
  GizmoOrientation,
  GizmoAxisColorPreset,
  GizmoUpAxis,
  GizmoAxisConfig,
  GizmoPresetView,
  OrbitDelta,
  GizmoHitRegion,
  Vec3,
  ProjectedArm,
  ChatMessageRole,
  ChatMessageStatus,
  ChatToolCallStatus,
  ChatAttachmentData,
  ChatToolCallData,
  ChatMessageData,
  ChatPanelDensity,
  ChatPanelProps,
  ChatMessageListProps,
  ChatMessageProps,
  ChatBubbleProps,
  ChatInputProps,
  ChatTypingIndicatorProps,
  ChatToolCallProps,
  ChatCodeBlockProps,
  ChatAttachmentChipProps,
  ChatContextChipProps,
  ChatEmptyStateProps,
  ChatActionBarProps,
  ChatInputToolbarProps,
  ChatMarkdownRendererProps,
  ChatMessageListScrollApi,
  UseChatMessagesOptions,
  UseChatMessagesReturn,
  UseChatInputOptions,
  UseChatInputReturn,
  UseChatScrollOptions,
  UseChatScrollReturn,
} from '@/components/editor';
export type {
  StatusBarProps,
  StatusBarSize,
  StatusBarVariant,
  StatusBarSectionProps,
  StatusBarSectionSide,
  StatusBarItemProps,
  ToolbarProps,
  ToolbarOrientation,
  ToolbarSize,
  ToolbarButtonProps,
  ToolbarButtonVariant,
  ToolbarToggleProps,
  ToolbarGroupProps,
  ToolbarSeparatorProps,
  ToolbarSpacerProps,
  MenuBarProps,
  MenuBarSize,
  MenuBarMenuProps,
  MenuBarItemProps,
  MenuBarSubProps,
  MenuBarSeparatorProps,
  FloatingPanelProps,
  FloatingManagerProps,
  Position,
  FloatingPanelSize,
  AppShellProps,
  AppShellSlotProps,
  AppShellToolbarSlotProps,
  AppShellContextValue,
  ToolbarPosition,
} from '@/components/shell';

// Types
export type { BaseComponent, Size, Variant } from '@/types/common';

// Utility Types for better DX
export type {
  Brand,
  DeepPartial,
  DeepReadonly,
  KeyOf,
  LiteralUnion,
  NonEmptyArray,
  Prettify,
  RequireFields,
  StrictExclude,
  ValueOf,
} from '@/types/utilities';

// Utilities
export { cn } from '@/utils/cn';
export { cx } from '@/utils/cx';
export {
  animBlink,
  animFadeIn,
  animPulse,
  animSpin,
  animWave,
  blinkKeyframe,
  fadeInKeyframe,
  pulseKeyframe,
  spinKeyframe,
  waveKeyframe,
} from '@/utils/animations';
