name: Deploy Storybook

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'stories/**'
      - '.storybook/**'
      - 'package.json'
      - 'public/**'
  
  workflow_dispatch:

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Storybook
        run: npm run build-storybook
      
      - name: Create proper Pages structure
        run: |
          # Create the deployment directory
          mkdir -p deploy
          
          # Copy the landing page to root
          if [ -f "public/index.html" ]; then
            cp public/index.html deploy/index.html
            echo "✅ Copied landing page"
          else
            echo "❌ Landing page not found at public/index.html"
            ls -la public/ || echo "Public directory doesn't exist"
          fi
          
          # Move storybook build to /storybook subdirectory
          if [ -d "storybook-static" ]; then
            mv storybook-static deploy/storybook
            echo "✅ Moved Storybook to /storybook/"
          else
            echo "❌ Storybook build not found"
            ls -la
          fi
          
          # Verify the structure
          echo "📁 Final deployment structure:"
          find deploy -type f | head -10
          
          # Check that both key files exist
          if [ -f "deploy/index.html" ] && [ -f "deploy/storybook/index.html" ]; then
            echo "✅ Both landing page and Storybook are ready"
          else
            echo "❌ Missing files:"
            ls -la deploy/
            ls -la deploy/storybook/ || echo "Storybook directory missing"
          fi
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './deploy'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4